services:

  # Database services
  timescaledb:
    container_name: timescaledb
    image: timescale/timescaledb:latest-pg16
    ports:
      - "15432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: ${TIMESCALEDB_PASS}
    volumes:
      - timescaledb-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '16379:6379'
    restart: always
    command: redis-server --save 20 1

  # Frontend services
  frontend:
    env_file: .env
    build:
      dockerfile: Dockerfile
      context: frontend/
    image: souravsaha/watchtower:frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8000:8000"

  # Backend services
  backend:
    env_file: .env
    build:
      dockerfile: Dockerfile
      context: backend/
    image: souravsaha/watchtower:backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "8001:8000"

volumes:
  timescaledb-data: