# ---------------------------------------------------------------------------
# This file configures the New Relic Python Agent.
# ---------------------------------------------------------------------------

[newrelic]
# license_key =
app_name = watchtower-backend

# New Relic offers distributed tracing for monitoring and analyzing modern
# distributed systems.Enable distributed tracing.
distributed_tracing.enabled = true
monitor_mode = true

# "critical", "error", "warning", "info" and "debug".
log_level = info
ssl = true
high_security = false

attributes.enabled = true
attributes.include = request.parameters.*

transaction_tracer.enabled = true
transaction_tracer.transaction_threshold = apdex_f
transaction_tracer.record_sql = raw
transaction_tracer.stack_trace_threshold = 0.5
transaction_tracer.explain_enabled = true
transaction_tracer.explain_threshold = 0.5
transaction_tracer.function_trace =
error_collector.enabled = true
error_collector.ignore_errors =
browser_monitoring.auto_instrument = true
thread_profiler.enabled = true

# ---------------------------------------------------------------------------

[newrelic:production]
monitor_mode = true

# ---------------------------------------------------------------------------
