name: build-backend

on:
#  push:
#    branches:
#      - main
#    paths:
#      - 'backend/**'
  workflow_dispatch:

concurrency:
  group: build-backend
  cancel-in-progress: true

jobs:

  build_X64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Service
      run: BUILD_ARCH=X64 docker compose build backend

    - name: Push docker images
      run: BUILD_ARCH=X64 docker compose push


  build_ARM64:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Service
        run: BUILD_ARCH=ARM64 docker compose -f docker-compose-build.yml build backend

      - name: Push docker images
        run: BUILD_ARCH=ARM64 docker compose -f docker-compose-build.yml push


  manifest:
    needs: [build_X64, build_ARM64]
    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Remove old manifest
      continue-on-error: true
      run: docker manifest rm "souravsaha/watchtower:backend"

    - name: Create manifest
      run: |
        docker manifest create "souravsaha/watchtower:backend" \
        --amend  "souravsaha/watchtower:backend-X64" \
        --amend "souravsaha/watchtower:backend-ARM64"
        docker manifest annotate --arch amd64 "souravsaha/watchtower:backend" "souravsaha/watchtower:backend-X64"

    - name: Push manifest
      run: docker manifest push "souravsaha/watchtower:backend"